version: '3'
services:
    nginx:
        image: nginx:1.13.8
        container_name: nginx
        networks:
            - production-network
        ports:
            - "80:80"
        depends_on:
            - "backend"
            - "frontend"
        volumes:
            - "./frontend/dist:/var/www/frontend"
            - "./frontend/package-lock.json:/usr/src/app/package-lock.json"
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./uwsgi_params:/etc/nginx/uwsgi_params"

    frontend:
        volumes:
            - "./frontend/dist:/usr/src/app/dist"
        command: npm run build

    backend:
        ports:
            - "8000:8000"
        command:  bash -c "python3 manage.py migrate && uwsgi --http :8000 --module backend.wsgi"

    mysql:
        volumes:
            - "./volumes/mysql:/var/lib/mysql"
