version: '3'
services:
    frontend:
        image: geovanecomp/britecorefrontend:1.0
        build:
            dockerfile: ./Dockerfile.production
            context: ./frontend
        ports:
            - "80:80"
        volumes:
            - "./frontend/nginx.conf:/etc/nginx/nginx.conf"
            - "./frontend/uwsgi_params:/etc/nginx/uwsgi_params"

    backend:
        image: geovanecomp/britecorebackend:1.0
        ports:
            - "8000:8000"
        command:  bash -c "python3 manage.py migrate && uwsgi --http :8000 --module backend.wsgi"

    mysql:
        volumes:
            - "./volumes/mysql:/var/lib/mysql"
