version: '3'
services:
    frontend:
        container_name: frontend
        networks:
            - production-network
        depends_on:
            - "backend"

    backend:
        container_name: backend
        networks:
            - production-network
        build:
            context: ./backend
        depends_on:
            - "mysql"
        links:
            - "mysql"

    mysql:
        container_name: mysql
        networks:
            - production-network
        image: mysql:5.7
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_DATABASE=britecore_insurance_system
        restart: always
        ports:
            - "3306:3306"
        # volumes:
            # - "./backend/queries/createschema.sql:/docker-entrypoint-initdb.d/createschema.sql"

networks:
    production-network:
        driver: bridge
